name: 'Check path changes'
description: 'Detects if files under a given path have changed between two Git refs and sets changed=true/false for conditional steps.'
inputs:
  path:
    description: 'Path prefix to watch (e.g. mon-dossier). Files under this path trigger changed=true.'
    required: true
  before:
    description: 'Git ref before (e.g. previous commit). Defaults to github.event.before on push.'
    required: false
    default: ${{ github.event.before }}
  after:
    description: 'Git ref after (e.g. current commit). Defaults to github.sha.'
    required: false
    default: ${{ github.sha }}
outputs:
  changed:
    description: '"true" if any file under the path changed between before and after, otherwise "false".'
    value: ${{ steps.check.outputs.changed }}
runs:
  using: 'composite'
  steps:
    - id: check
      run: python3 "${{ github.action_path }}/main.py"
      shell: bash
      env:
        INPUT_PATH: ${{ inputs.path }}
        INPUT_BEFORE: ${{ inputs.before }}
        INPUT_AFTER: ${{ inputs.after }}
