name: 'Check path changes'
description: 'Detects if files under a given path have changed between two Git refs and sets changed=true/false for conditional steps.'
inputs:
  path:
    description: 'Path prefix to watch (e.g. mon-dossier). Files under this path trigger changed=true.'
    required: true
  before:
    description: 'Git ref before (e.g. previous commit). Defaults to github.event.before on push.'
    required: false
    default: HEAD~1
  after:
    description: 'Git ref after (e.g. current commit). Defaults to github.sha.'
    required: false
    default: HEAD
outputs:
  changed:
    description: '"true" if any file under the path changed between before and after, otherwise "false".'
runs:
  using: 'docker'
  image: 'Dockerfile'
